### ISSUE TITLE
Plugin not installed Error

### ISSUE THREAD

**Issue by msolima** [zyra/cordova-plugin-stripe#15]
Am always getting [ 'plugin not installed' ] when trying to use this.

I did cordova plugin add cordova-plugin-stripe
then installed the npm version of the stripe plugin.

Then when I try to use cordova.plugins.stripe.createCardToken(card, onSuccess, onError);

am always getting onError with "Plugin not installed"

any idea what's happening?

**Comment by ihadeed** [comment]
Sorry for the late response.

I'm unable to reproduce this issue. The only time I think this error can occur, is if you are using the Ionic Native wrapper and trying to use the plugin via `ionic serve`.
