### ISSUE TITLE
CardHolder Name not going to Stripe backend when using IOS 

### ISSUE THREAD

**Issue by ihadeed** [zyra/cordova-plugin-stripe#17]
_From @wasifkarim on June 3, 2017 21:4_

I have tested in both Android and IOS. The cardholder name is present before the request is submitted to createToken. In IOS, the strip payments section does not show the customer name. When the payment is submitted using Android, the customer name appears. 

_Copied from original issue: zyra/ionic-image-loader#59_

**Comment by ihadeed** [comment]
Thanks for reporting this issue @wasifkarim

I will look into it and get back to you.

**Comment by ihadeed** [comment]
@wasifkarim this issue should be resolve in the latest version. Please update the plugin and let me know if you're still experiencing issues.

**Comment by GrosJob** [comment]
Hello,

I'm experiencing exactly the same problem, as the name is linked with the card on Android, but with iOS the cards appears without any name on Stripe back-office.
As banks refuse a lot of cards when no name is given with it, I would need to be able to correct this and guess other persons might face the same problem.

Thank you!
