### ISSUE TITLE
Setting Stripe Publishable Key dynamically

### ISSUE THREAD

**Issue by wasifkarim** [zyra/cordova-plugin-stripe#18]
I have an integration which requires multiple stripe accounts to be used. The publishable keys are stored in the database. When I am ready to generate the stripe token, I m calling the setPublishableKey with the appropriate key for that account. It seems that only the first publishable key that was set can be used to do further credit card processing to generate the token. Can this be enhanced to allow multiple stripe accounts to be used? Stripe supports that and allows that. Can you provide your input on this? Thanks for all your hard work and effort.

**Comment by ihadeed** [comment]
Just call setPublishableKey.. Every time you call that method, it changes the key for any subsequent API calls.

**Comment by wasifkarim** [comment]
Ibby,

I appreciate your prompt response. In doing further testing, I realized
this is issue on IOS only. It works perfectly in Android. Is this something
you can look into? We are about to go live and this will stop us. I will
really appreciate your help in this matter. Thanks.

**Comment by wasifkarim** [comment]
I have fixed the issue. in CordovaStripe.m, I commented out the check to see if client is nill before initializing the client. This way, it will initialize it everytime and get new publishable key everytime. I am sure there is a better way to fix it but this was quick and dirty for me.

**Comment by ihadeed** [comment]
Just pushed a commit to fix this. If a stripe client already exists, it will update the publishable key for that instance as well. No need to recreate the client every time.

Thanks for pointing this out!
