### ISSUE TITLE
Got the following issue "cordova_not_available"

### ISSUE THREAD

**Issue by miguelfoko** [zyra/cordova-plugin-stripe#21]
Can somebody help me please?

I got the '**cordova_not_available**' issue when trying to use **createCardToken** method of stripe API.

I'm using the following tutorial **https://github.com/zyra/cordova-plugin-stripe**. My aim is to integrate Stripe in my Ionic Application. My IONIC Version is 3.3 and my cordova version is 6.2.3

Excuse me for my poor english

**Comment by ihadeed** [comment]
Are you trying this using `ionic serve` command? 

The plugin only works on Cordova platforms.

**Comment by miguelfoko** [comment]
Hi ihadeed, Not sure to understand what you want to say, can you please more explain your suggestion?

**Comment by ihadeed** [comment]
How are you testing the app? Are you testing it while running `ionic serve` command? Or are you running it on a device?

**Comment by miguelfoko** [comment]
Hi @ihadeed. Thanks a lot for your answer, effectively I was running it using **ionic serve**, now that I tried to run on a device it works.

Thanks Thanks Thanks
