### ISSUE TITLE
ERROR: AuthenticationError is never thrown in the body ANDROID

### ISSUE THREAD

**Issue by virtapoika** [zyra/cordova-plugin-stripe#23]
Hi, I've got the following error

`/platforms/android/src/com/zyramedia/cordova/stripe/CordovaStripe.java:59: error: exception AuthenticationException is never thrown in body of corresponding try statement
    } catch (AuthenticationException e) {
      ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
`

When trying to build android for the project. iOS and browser work fine! Any ideas?

**Comment by ihadeed** [comment]
Thanks for reporting this.

I updated the SDK versions recently, looks like I missed a change. I will fix this soon.

In the meanwhile you can use older versions of this plugin.

**Comment by ihadeed** [comment]
This is fixed now, run the following commands to ensure you have the latest version:
```
cordova plugin rm cordova-plugin-stripe
cordova plugin add cordova-plugin-stripe@latest
```

**Comment by virtapoika** [comment]
Thanks! Awesome work!
> Ibby Hadeed <notifications@github.com> kirjoitti 6.7.2017 kello 9.47:
> 
> cordova plugin add cordova-plugin-stripe@latest
>
