### ISSUE TITLE
Localizing error messages

### ISSUE THREAD

**Issue by mwiley63** [zyra/cordova-plugin-stripe#24]
Is there any way to localize error messages using this plugin?

**Comment by ihadeed** [comment]
No, but this is a good idea. I will look into it. I will check if the native plugin is capable of returning localized error messages.

**Comment by ihadeed** [comment]
Looks like iOS is already configured to return localized error messages. I just pushed a commit to do the same on Android.

**Comment by ihadeed** [comment]
Just published `cordova-plugin-stripe@1.5.3`. Please update to the latest version and let me know if you're still experiencing issues.

**Comment by mwiley63** [comment]
Wow, thank you!  I will give it a try.

**Comment by mwiley63** [comment]
iOS is working!  I localized using the following files from stripe-ios:  https://github.com/stripe/stripe-ios/tree/master/Stripe/Resources/Localizations

**Comment by mwiley63** [comment]
I was unable to get Android to localize, it looks like the Android Stripe SDK is missing localizations:  https://github.com/stripe/stripe-android/issues/283

**Comment by ihadeed** [comment]
Thanks for the feedback @mwiley63 

Let me know if there's any further action I need to take on my end.
