### ISSUE TITLE
Card Reader

### ISSUE THREAD

**Issue by slodolce** [zyra/cordova-plugin-stripe#27]
Hi guys,

Curious if this plugin supports any of these card readers?

https://stripe.com/works-with/categories/card-readers-pos

Thanks!

**Comment by ihadeed** [comment]
This plugin wraps the following two SDKs:

https://stripe.com/docs/mobile/android (or full SDK [here](https://github.com/stripe/stripe-android))
https://stripe.com/docs/mobile/ios (or full SDK [here](https://github.com/stripe/stripe-ios))

The features you requested aren't included in their mobile SDKs, so I can't add them here. I will have to create new plugins to wrap the other SDKs mentioned on that page.
