### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by erperejildo** [zyra/cordova-plugin-stripe#39]
When you say "Once you have the token, you can now send it to your backend so you can charge the customer later on" what do you mean?

I'm trying to find info here: https://stripe.com/docs/charges but can't see any javascript reference

**Comment by ihadeed** [comment]
This plugin communicates with Stripe's servers via their mobile SDKs. It's only job is to send credit card information safely to Stripe, and retrieve a token that represents that credit card. Once you have the token, you can instruct your back end server to do things with it, such as: (1) charge the credit card, or (2) attach it to a customer's file. 

In the page you sent me, you will notice that they are sending a parameter to stripe's API named `source`. That parameter is basically the credit card token that you got from the mobile SDK/plugin.

**Comment by erperejildo** [comment]
Ok, so something like this maybe?
`$http.post('https://api.stripe.com/v1/charges', token)`

**Comment by ihadeed** [comment]
Follow the examples here: https://stripe.com/docs/charges

You don't want to ask stripe to charge a card via your client side app, because then you will need to include your secret token in the code. You need a backend.

**Comment by erperejildo** [comment]
Don't understand what do you mean when you say that "I need a backend".

My app is just a frontend app with no backend at all. Can I send this toke (which I get properly) to any Stripe's API?

**Comment by ihadeed** [comment]
You can but it's not secure. You can't charge a customer without your
secret key. And the secret key should not be included in your frontend
application. This is all mentioned in stripe's API.

As far as I know there is no way to charge via stripe securely without some
sort of backend. You can setup a "Serverless" server on AWS lambda for free
or almost free.

Regards,
Ibby Hadeed

**Comment by erperejildo** [comment]
Ok fair enough. In that case I'm afraid I can't use it unless I have Firebase

**Comment by ihadeed** [comment]
AFAIK Firebase is a database-as-a-service, so that wouldn't help either. You need to setup a server manually, use [Serverless](https://serverless.com/), or use an PaaS like [Heroku](https://www.heroku.com/).
