### ISSUE TITLE
createCardToken return token doesn't contain fingerprint

### ISSUE THREAD

**Issue by mewild** [zyra/cordova-plugin-stripe#41]
The stripe API says that a token has a value called fingerprint that can be used to uniquely identify card numbers.

Obviously for security reasons I do not transfer full card numbers over the network ever. Instead I transfer the fingerprint of each card. 

When I create a card token I would like to compare fingerprints to make sure Im not adding the same card again and again. 

When i try to get the fingerprint of the card it does not exist?

Is this something that can be changed?

**Comment by mewild** [comment]
Just seen the typings file does indeed contain the fingerprint value.

Why does my ionic flag up that it doesn't exist?


> Property 'fingerprint' does not exist on type '{ brand: string; exp_month: number; exp_year: number; 
>             funding: string; last4: string; }'.

**Comment by ihadeed** [comment]
Hey there,

I don't recall adding a fingerprint parameter for the create token methods. I'll be happy to add that though. 

Could you please direct me to the stripe doc page that demonstrate it's usage and/or explain its functionality?

**Comment by mewild** [comment]
Reading more while trying to find some documentation to send to you I found that this is expected behaviour.

Stripe have implemented it so that you can only obtain a fingerprint when creating a token with a secret key. Therefore I need to create the token on the server side if I want to have a fingerprint.

Closing as everything seems to be in order regarding this functionality. 

Thanks.
