### ISSUE TITLE
How do I add payment source

### ISSUE THREAD

**Issue by eugenemaning** [zyra/cordova-plugin-stripe#43]
I get this error when trying to subscribe to a plan.

Error: This customer has no attached payment source

**Comment by ihadeed** [comment]
You need to:
1. Get a token for credit card / bank account
2. Send it to your back end
3. Send it to Stripe and attach it to a customer's profiel
4. Charge them / subscribe.. etc

**Comment by eugenemaning** [comment]
Thank you very much Ihadeed
