### ISSUE TITLE
ionic-native parameter name mismatch

### ISSUE THREAD

**Issue by geo242** [zyra/cordova-plugin-stripe#48]
Ionic native typescript defs have the postal code param as "postal_code" but the native code looks for "postalCode". This is just an FYI that I created a PR to fix it in ionic native.

https://github.com/ionic-team/ionic-native/pull/2520

I would suggest that the casing of the parameters be made consistent throughout though. It's kinda weird to have some properties snake case and some camel case.

**Comment by danielsogl** [comment]
Closed with: https://github.com/ionic-team/ionic-native/pull/2520
