### ISSUE TITLE
Ionic Stripe plugin installation

### ISSUE THREAD

**Issue by webgump** [zyra/cordova-plugin-stripe#52]
Hi,

I am trying to install the ionic stripe plugin on our application.
I followed the steps from the documentation https://ionicframework.com/docs/native/stripe/
I always get the error "plugin_not_installed"
Have you any ideas why ?

Thanks,
X.Quièvre

**Comment by webgump** [comment]
It does not work in ngAfterViewInit method, but it works when calling createCardToken method in another method triggered by a button

**Comment by patrickchoi** [comment]
Suggest that this be put in the readme. In the Ionic page it seems to suggest you should put the sample code in the constructor, which will always return the plugin not installed error. Took me an hour to figure this out, moving to its own function worked fine.
