### ISSUE TITLE
not issue but question is: Stripe in createTokenWithPayment not found

### ISSUE THREAD

**Issue by darshansarvaiyasa** [zyra/cordova-plugin-stripe#55]
createTokenWithPayment this function can't find in plugin,
i need help for apple pay token to convert STPToken for stripe

**Comment by ihadeed** [comment]
are you using the beta branch?

**Comment by darshansarvaiyasa** [comment]
I don't know but i m using this command 'ionic cordova plugin add cordova-plugin-stripe'
