### ISSUE TITLE
SCA integration 

### ISSUE THREAD

**Issue by AhmadAyyaz1993** [zyra/cordova-plugin-stripe#69]
I just want to know that if we have support for SCA in this plugin or plans for implementing it near future?

**Comment by ihadeed** [comment]
@AhmadAyyaz1993 

Support for SCA is implemented in the [Capacitor](https://capacitor.ionicframework.com/) version: https://github.com/zyra/capacitor-stripe

[This PR](https://github.com/zyra/cordova-plugin-stripe/pull/68) is to merge that implementation into this repo to make it work for Cordova.

It works but requires the following plugins to be installed on Cordova:
- cordova-plugin-androidx
- cordova-plugin-androidx-adapter
- cordova-support-kotlin

New version highlights:
* All the essential features are working and tested (card, bank, pii, and source tokens, payment intents, setup intents, google pay, apple pay)
* UI components were partially implemented but they're removed for now. Will implement if https://github.com/stripe/stripe-android/issues/1778 is resolved.
* Payment methods (listing customer cards) is implemented but not very well tested.

In the near future payment methods will be tested more thoroughly  to squeeze out any existing bugs. Once things are looking stable I'll do another round of quick refactoring to port both the Android + iOS implementations here.

**Comment by AhmadAyyaz1993** [comment]
Thanks  for the information.
